// src/lib/generators/angular-generator.ts
import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const logger = createLogger('angular-generator');

/**
 * Angular Generator - Generates Angular components and projects
 */
export class AngularGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    architecture: Architecture,
    stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    // TODO: Implement Angular project generation
    const files: IGeneratedFile[] = [{
      path: 'README.md',
      content: `# ${projectName}\n\nAngular project generated by UIForge MCP.\n\nTODO: Implement Angular project generation.`
    }];

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['@radix-ui/themes', 'class-variance-authority'];
  }

  protected getRadixDependencies(): string[] {
    return ['@radix-ui/themes'];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/tailwindcss'];
  }

  protected getPrimeVueDependencies(): string[] {
    return [];
  }

  protected getMaterialDependencies(): string[] {
    return ['@angular/material'];
  }

  protected getShadcnImports(): string[] {
    return [];
  }

  protected getRadixImports(): string[] {
    return [];
  }

  protected getHeadlessUIImports(): string[] {
    return [];
  }

  protected getPrimeVueImports(): string[] {
    return [];
  }

  protected getMaterialImports(): string[] {
    return [];
  }

  protected generateShadcnComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md max-w-md">
      <h2 class="text-xl font-bold mb-2">${componentName}</h2>
      <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using shadcn/ui styles</p>
      <button class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">Click me</button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  // TODO: Implement component logic
}`;
  }

  protected generateRadixComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Radix UI patterns</p>
          <button (click)="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateHeadlessUIComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="toggleDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Headless UI patterns</p>
          <button (click)="toggleDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  toggleDialog() {
    this.isDialogOpen = !this.isDialogOpen;
  }
}`;
  }

  protected generatePrimeVueComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded">
        <i class="fas fa-plus mr-2"></i>${componentName}
      </button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
        <div class="bg-white p-6 rounded-lg shadow-lg max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using PrimeVue styles</p>
          <button (click)="closeDialog()" class="bg-gray-500 hover:bg-gray-600 text-white px-4 py-2 rounded">
            <i class="fas fa-times mr-2"></i>Close
          </button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateMaterialComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <mat-button (click)="openDialog()" color="primary" raised>${componentName}</mat-button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  constructor(private dialog: MatDialog) {}

  openDialog() {
    this.dialog.open(DialogContentComponent, {
      data: { title: '${componentName}', message: 'A ${componentType.toLowerCase()} component using Material Design' }
    });
  }
}

@Component({
  selector: 'dialog-content',
  template: \`
    <div class="bg-white p-6 rounded-lg">
      <h2 mat-dialog-title>{{ data.title }}</h2>
      <div mat-dialog-content>{{ data.message }}</div>
      <div mat-dialog-actions>
        <button mat-button (click)="dialogRef.close()">Close</button>
      </div>
    </div>
  \`
})
export class DialogContentComponent {
  constructor(public dialogRef: any) {}
}`;
  }

  protected generateTailwindComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md">
      <h2 class="text-xl font-bold mb-4">${componentName}</h2>
      <p class="text-gray-600 mb-4">A ${componentType.toLowerCase()} component using Tailwind CSS</p>
      <button
        class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
        (click)="handleClick()"
      >
        Click me
      </button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  handleClick() {
    console.log('Button clicked');
  }
}`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/app/components/${componentName}.component.ts`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { ${componentName}Component } from './${componentName}.component';

describe('${componentName}Component', () => {
  let component: ${componentName}Component;
  let fixture: ComponentFixture<${componentName}Component>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [${componentName}Component]
    }).compileComponents();

    fixture = TestBed.createComponent(${componentName}Component);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should render component type', () => {
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.textContent).toContain('${componentType.toLowerCase()}');
  });
});
`;

    return {
      path: `src/app/components/${componentName}.component.spec.ts`,
      content,
    };
  }
}

// src/lib/generators/react-generator.ts
import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const logger = createLogger('react-generator');

/**
 * React Generator - Generates React components and projects
 */
export class ReactGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  /**
   * Generate a complete React project
   */
  generateProject(
    projectName: string,
    architecture: Architecture,
    stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    const files: IGeneratedFile[] = [];

    // Package.json
    files.push(this.createPackageJsonFile(projectName, stateManagement));

    // TypeScript config
    files.push(this.createTsConfigFile());

    // Vite config
    files.push(this.createViteConfigFile());

    // README
    files.push(this.createReadmeFile(projectName));

    // Main App component
    files.push(this.createAppComponent(designContext));

    // Index.html
    files.push(this.createIndexHtmlFile(projectName));

    // CSS/Tailwind config
    files.push(this.createTailwindConfig(designContext));

    // State management setup
    if (stateManagement !== 'none') {
      files.push(...this.createStateManagementFiles(stateManagement, designContext));
    }

    this.logComplete('project', projectName, files.length);
    return files;
  }

  /**
   * Generate a React component
   */
  generateComponent(
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Storybook file (optional)
    if (process.env.NODE_ENV !== 'production') {
      files.push(this.createStorybookFile(componentName, componentType, designContext));
    }

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  private createPackageJsonFile(projectName: string, stateManagement: StateManagement): IGeneratedFile {
    const dependencies: Record<string, string> = {
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      'react-router-dom': '^6.8.0',
      'clsx': '^1.2.1',
    };

    const devDependencies: Record<string, string> = {
      '@types/react': '^18.0.27',
      '@types/react-dom': '^18.0.10',
      '@vitejs/plugin-react': '^3.1.0',
      'vite': '^4.1.0',
      'tailwindcss': '^3.2.7',
      'autoprefixer': '^10.4.14',
      'postcss': '^8.4.21',
      '@testing-library/react': '^14.0.0',
      '@testing-library/jest-dom': '^5.16.5',
      'vitest': '^0.29.1',
    };

    // Add state management dependencies
    if (stateManagement === 'zustand') {
      dependencies.zustand = '^4.3.6';
    }

    return {
      path: 'package.json',
      content: this.createPackageJson(projectName, dependencies, devDependencies),
    };
  }

  private createTsConfigFile(): IGeneratedFile {
    return {
      path: 'tsconfig.json',
      content: this.createTsConfig(),
    };
  }

  private createViteConfigFile(): IGeneratedFile {
    return {
      path: 'vite.config.ts',
      content: this.createViteConfig(),
    };
  }

  private createReadmeFile(projectName: string): IGeneratedFile {
    return {
      path: 'README.md',
      content: this.createReadme(projectName),
    };
  }

  private createAppComponent(designContext: IDesignContext): IGeneratedFile {
    const content = `import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import './App.css';

function App() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '${designContext.colorPalette.background}' }}>
      <header className="p-6">
        <h1 className="text-3xl font-bold" style={{ color: '${designContext.colorPalette.primary}' }}>
          Welcome to ${designContext.typography.fontFamily}
        </h1>
      </header>
      <main className="container mx-auto px-4 py-8">
        <p style={{ color: '${designContext.colorPalette.foreground}' }}>
          Your React application is ready!
        </p>
      </main>
    </div>
  );
}

export default App;
`;

    return {
      path: 'src/App.tsx',
      content,
    };
  }

  private createIndexHtmlFile(projectName: string): IGeneratedFile {
    return {
      path: 'index.html',
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    };
  }

  private createTailwindConfig(designContext: IDesignContext): IGeneratedFile {
    return {
      path: 'tailwind.config.js',
      content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '${designContext.colorPalette.primary}',
        secondary: '${designContext.colorPalette.secondary}',
        background: '${designContext.colorPalette.background}',
        foreground: '${designContext.colorPalette.foreground}',
      },
      fontFamily: {
        sans: ['${designContext.typography.fontFamily}', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
`,
    };
  }

  private createStateManagementFiles(stateManagement: StateManagement, designContext: IDesignContext): IGeneratedFile[] {
    const files: IGeneratedFile[] = [];

    if (stateManagement === 'zustand') {
      files.push({
        path: 'src/store/useAppStore.ts',
        content: `import { create } from 'zustand';

interface AppState {
  count: number;
  increment: () => void;
  decrement: () => void;
}

export const useAppStore = create<AppState>((set) => ({
  count: 0,
  increment: () => set((state) => ({ count: state.count + 1 })),
  decrement: () => set((state) => ({ count: state.count - 1 })),
}));
`,
      });
    }

    return files;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, any>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const propsInterface = Object.keys(props).length > 0
      ? `interface ${componentName}Props {\n${Object.entries(props)
          .map(([key, type]) => `  ${key}: ${type};`)
          .join('\n')}\n}\n\n`
      : '';

    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      // Use component library-specific generation
      const imports = this.getComponentLibraryImports(componentLibrary).join('\n');
      const componentCode = this.generateComponentLibraryCode(componentType, props, componentLibrary);

      content = `${propsInterface}${imports}

${componentCode}

export default ${componentName};`;
    } else {
      // Use default Tailwind CSS generation
      content = `${propsInterface}import React from 'react';
import clsx from 'clsx';

export const ${componentName}: React.FC<${componentName}Props> = (${Object.keys(props).length > 0 ? '{' : ''}${Object.keys(props).join(', ')}${Object.keys(props).length > 0 ? '}' : ''}) => {
  return (
    <div
      className={clsx(
        'p-4 rounded-lg',
        'bg-white',
        'shadow-md',
        'border border-gray-200'
      )}
      style={{
        backgroundColor: '${designContext.colorPalette.background}',
        color: '${designContext.colorPalette.foreground}',
        borderColor: '${designContext.colorPalette.muted}',
      }}
    >
      <h2 className="text-xl font-semibold mb-2" style={{ color: '${designContext.colorPalette.primary}' }}>
        ${componentName}
      </h2>
      <p>
        This is a ${componentType} component with custom styling.
      </p>
    </div>
  );
};

export default ${componentName};`;
    }

    return {
      path: `src/components/${componentName}.tsx`,
      content,
    };
  }

  private createStorybookFile(
    componentName: string,
    componentType: string,
    designContext: IDesignContext
  ): IGeneratedFile {
    const content = `import type { Meta, StoryObj } from '@storybook/react';
import { ${componentName} } from './${componentName}';

const meta: Meta<typeof ${componentName}> = {
  title: 'Components/${componentName}',
  component: ${componentName},
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {},
};

export const WithCustomProps: Story = {
  args: {
    // Add custom props here
  },
};
`;

    return {
      path: `src/components/${componentName}.stories.tsx`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    designContext: IDesignContext
  ): IGeneratedFile {
    const content = `import { render, screen } from '@testing-library/react';
import { ${componentName} } from './${componentName}';

describe('${componentName}', () => {
  it('renders without crashing', () => {
    render(<${componentName} />);
    expect(screen.getByText('${componentName}')).toBeInTheDocument();
  });

  it('displays the component type', () => {
    render(<${componentName} />);
    expect(screen.getByText(/${componentType}/i)).toBeInTheDocument();
  });
});
`;

    return {
      path: `src/components/${componentName}.test.tsx`,
      content,
    };
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return [
      '@radix-ui/react-slot',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-select',
      '@radix-ui/react-tabs',
      '@radix-ui/react-toast',
      'class-variance-authority',
      'clsx',
      'tailwind-merge',
      'lucide-react'
    ];
  }

  protected getRadixDependencies(): string[] {
    return [
      '@radix-ui/react-slot',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-select',
      '@radix-ui/react-tabs',
      '@radix-ui/react-toast'
    ];
  }

  protected getHeadlessUIDependencies(): string[] {
    return [
      '@headlessui/react',
      '@heroicons/react'
    ];
  }

  protected getPrimeVueDependencies(): string[] {
    return [
      'primevue',
      'primeicons'
    ];
  }

  protected getMaterialDependencies(): string[] {
    return [
      '@mui/material',
      '@mui/icons-material'
    ];
  }

  protected getShadcnImports(): string[] {
    return [
      "import { cn } from \"lib/utils\";",
      "import { Button } from \"components/ui/button\";",
      "import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from \"components/ui/card\";",
      "import { Input } from \"components/ui/input\";",
      "import { Label } from \"components/ui/label\";"
    ];
  }

  protected getRadixImports(): string[] {
    return [
      "import * as Dialog from \"@radix-ui/react-dialog\";",
      "import * as DropdownMenu from \"@radix-ui/react-dropdown-menu\";",
      "import * as Select from \"@radix-ui/react-select\";",
      "import * as Tabs from \"@radix-ui/react-tabs\";"
    ];
  }

  protected getHeadlessUIImports(): string[] {
    return [
      "import { Button } from \"@headlessui/react\";",
      "import { Dialog } from \"@headlessui/react\";",
      "import { Menu } from \"@headlessui/react\";",
      "import { Transition } from \"@headlessui/react\";"
    ];
  }

  protected getPrimeVueImports(): string[] {
    return [
      "import Button from \"primevue/button\";",
      "import Dialog from \"primevue/dialog\";",
      "import InputText from \"primevue/inputtext\";",
      "import DataTable from \"primevue/datatable\";"
    ];
  }

  protected getMaterialImports(): string[] {
    return [
      "import Button from \"@mui/material/Button\";",
      "import Dialog from \"@mui/material/Dialog\";",
      "import TextField from \"@mui/material/TextField\";",
      "import Card from \"@mui/material/Card\";",
      "import CardContent from \"@mui/material/CardContent\";"
    ];
  }

  protected generateShadcnComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <Card className={cn("w-full max-w-md", props.className)}>
      <CardHeader>
        <CardTitle>${componentName}</CardTitle>
        <CardDescription>
          A ${componentType.toLowerCase()} component built with shadcn/ui
        </CardDescription>
      </CardHeader>
      <CardContent>
        <p>This is a ${componentType.toLowerCase()} component using shadcn/ui design system.</p>
        <Button className="mt-4">Click me</Button>
      </CardContent>
    </Card>
  )
}`;
  }

  protected generateRadixComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import * as Dialog from "@radix-ui/react-dialog"
import * as DropdownMenu from "@radix-ui/react-dropdown-menu"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <Dialog.Root>
      <Dialog.Trigger asChild>
        <button>${componentName}</button>
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/50" />
        <Dialog.Content className="fixed left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component using Radix UI primitives
          </Dialog.Description>
          <DropdownMenu.Root>
            <DropdownMenu.Trigger asChild>
              <button>Options</button>
            </DropdownMenu.Trigger>
            <DropdownMenu.Portal>
              <DropdownMenu.Content className="bg-white p-2 rounded-lg shadow-lg">
                <DropdownMenu.Item>Option 1</DropdownMenu.Item>
                <DropdownMenu.Item>Option 2</DropdownMenu.Item>
              </DropdownMenu.Content>
            </DropdownMenu.Portal>
          </DropdownMenu.Root>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}`;
  }

  protected generateHeadlessUIComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Button } from "@headlessui/react"
import { Dialog } from "@headlessui/react"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <div className="p-4">
      <Button onClick={() => {}}>${componentName}</Button>
      <Dialog open={false} onClose={() => {}}>
        <Dialog.Panel className="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component using Headless UI
          </Dialog.Description>
          <div className="mt-4">
            <Button onClick={() => {}}>Close</Button>
          </div>
        </Dialog.Panel>
      </Dialog>
    </div>
  )
}`;
  }

  protected generatePrimeVueComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    // Note: This would be used in a Vue generator, but we provide a React-compatible version
    return `import { Button } from "@headlessui/react"
import { Dialog } from "@headlessui/react"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  const [open, setOpen] = React.useState(false)

  return (
    <div className="p-4">
      <Button onClick={() => setOpen(true)}>${componentName}</Button>
      <Dialog open={open} onClose={() => setOpen(false)}>
        <Dialog.Panel className="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component (PrimeVue style)
          </Dialog.Description>
          <div className="mt-4">
            <Button onClick={() => setOpen(false)}>Close</Button>
          </div>
        </Dialog.Panel>
      </Dialog>
    </div>
  )
}`;
  }

  protected generateMaterialComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `import Button from '@mui/material/Button'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'

export function ${componentName}(${this.generatePropsInterface(props)}) {
  const [open, setOpen] = React.useState(false)

  return (
    <div className="p-4">
      <Button variant="contained" onClick={() => setOpen(true)}>
        ${componentName}
      </Button>
      <Dialog open={open} onClose={() => setOpen(false)}>
        <DialogTitle>${componentName}</DialogTitle>
        <DialogContent>
          <p>A ${componentType.toLowerCase()} component using Material UI</p>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </div>
  )
}`;
  }

  protected generateTailwindComponent(componentType: string, props: Record<string, any>): string {
    const componentName = this.formatComponentName(componentType);

    return `export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-xl font-bold mb-4">${componentName}</h2>
      <p className="text-gray-600 mb-4">
        A ${componentType.toLowerCase()} component using Tailwind CSS
      </p>
      <button
        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
        onClick={() => console.log('Button clicked')}
      >
        Click me
      </button>
    </div>
  )
}`;
  }

  private generatePropsInterface(props: Record<string, any>): string {
    const propKeys = Object.keys(props);
    if (propKeys.length === 0) return '';

    const propDefinitions = propKeys.map(key => {
      const value = props[key];
      let type = 'string';

      if (typeof value === 'boolean') type = 'boolean';
      else if (typeof value === 'number') type = 'number';
      else if (typeof value === 'object') type = 'any';

      return `${key}?: ${type}`;
    }).join(', ');

    return `{ ${propDefinitions} }`;
  }
}
